name: Build Assembly EXE

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up TASM and TLink
      run: |
        # 下载并安装 TASM 和 TLink
        choco install borland-c --version=5.5.1

    - name: Compile assembly to object file
      run: |
        # 在 Windows 环境中使用 TASM 编译汇编代码
        tasm Decimal_Hex.asm

    - name: Link object file to EXE
      run: |
        # 使用 TLink 链接生成 EXE 文件
        tlink Decimal_Hex.obj

    - name: Upload EXE as artifact
      uses: actions/upload-artifact@v2
      with:
        name: Decimal_Hex-exe
        path: Decimal_Hex.exe
